name: Every 10 Minutes Job

on:
  schedule:
    - cron: '*/5 * * * *'  # cron 표현식으로 10분마다 실행 (분: 0, 10, 20, 30, 40, 50)

jobs:
  ten_minutes_job:
    runs-on: ubuntu-latest

    steps:
      - name: Display current time
        run: |
          echo "Current Time : "
          echo "$(date + "%Y-%m-%dT%H:%M:%SZ")"
          echo "$(TZ=Asia/Seoul date +"%Y-%m-%dT%H:%M:%SZ")"
