name: Main Branch Commit Alert

on:
  push:
    branches:
      - main

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Send Notification
        env:
          SENDGRID_API_KEY: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          echo "Commit to main branch detected." | mail -s "Main Branch Commit" vvv343434345@gmail.com
