name: Hourly Job

on:
  schedule:
    - cron: '*/10 * * * *'  

jobs:
  hourly_job:
    runs-on: ubuntu-latest

    steps:
      - name: Display current time
        run: |
          echo "Current time: ${{ steps.set_date.outputs.current_time }}"
