name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Read mail receiver
        id: read-file
        run: echo "::set-output name=file_content::$(cat actions/mail_receiver.js)"
      
      - name: Set environment variable
        run: echo "FILE_CONTENT='${{ steps.read-file.outputs.file_content }}'" >> $RECEIVER_EMAIL

      - name: Install dependencies
        run: npm install nodemailer
      
      - name: Send email
        run: |
          node ./actions/sendEmail.js
        env:
          NODE_MAIL_SERVICE: ${{ secrets.NODE_MAIL_SERVICE }}
          NODE_MAIL_USER: ${{ secrets.NODE_MAIL_USER }}
          NODE_MAIL_PASS: ${{ secrets.NODE_MAIL_PASS }}
