name: Update Lotto File

on:
  push:
    branches:
      - main 

jobs:
  update-lotto:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.MY_TOKEN }} #test
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install axios

    - name: Run Node.js Script
      run: node actions/lotto.js

    - name: Commit and Push Changes
      run: |
        git config --global user.email "vvv3334@hanmail.net"
        git config --global user.name "bloodstrawberry"
        git add actions/lotto.json
        git commit -m "Update lotto file via GitHub Actions"
        git remote add origin_with_token https://$GH_TOKEN@github.com/bloodstrawberry/auto-test.git
        git push origin_with_token
